{{- if and (not .Values.database.existingSecret) (or .Values.database.url .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driftdetect.databaseSecretName" . }}
  labels:
    {{- include "driftdetect.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ include "driftdetect.databaseURL" . | quote }}
{{- end }}
---
{{- if and (not .Values.apiKeys.existingSecret) .Values.config.server.api_keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driftdetect.apiKeysSecretName" . }}
  labels:
    {{- include "driftdetect.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKeys.existingSecretKey }}: {{ join "," .Values.config.server.api_keys | quote }}
{{- end }}
